### ISSUE TITLE
Alle small Blocks checken!!! small reactors 

### ISSUE THREAD

**Issue by BahaZoo** [ruffst/New-Production#12]
![Reactor error](https://user-images.githubusercontent.com/96697123/148047231-f6900837-c3fb-4336-a1c4-4ddb898d3cf1.PNG)

**Comment by CaptainHarlock0006** [comment]
alle Small Blcoks ist weit gefasst. Bitte genauere Angaben. welcher Block in welcher Situation. am besten noch die Log vom Spiel anhängen.
