### ISSUE TITLE
starter ore detector fixn

### ISSUE THREAD

**Issue by BahaZoo** [ruffst/New-Production#13]

**Comment by ruffst** [comment]
Auch im Survival baubar ohne Forschung

![grafik](https://user-images.githubusercontent.com/13318761/148051943-9585b25b-0272-44f2-9ad0-83e711c88451.png)

**Comment by CaptainHarlock0006** [comment]
Block wurde geändert. Er kann nun zwar gefunden werden jedoch nicht mehr geplaced werden da die Components nur den Admins zur Verfügung stehen.
