### ISSUE TITLE
Small Grid Blöcke Panzerung

### ISSUE THREAD

**Issue by PottSau** [ruffst/New-Production#16]
Fehlen

**Comment by ruffst** [comment]
Welche genau? Welcher Gridtyp? Fehlt eventuell die Freischaltung per Milestone?

**Comment by ruffst** [comment]
![grafik](https://user-images.githubusercontent.com/13318761/148070205-7c46c046-0027-4ba5-931b-048ab9a28bcb.png)
Blöcke sind da aber nicht in der Pairgroup. Das ist ein Kompromiss, den wir eingehen mussten um die Forschung von Groß- und Kleinblöcken zu trennen
