### ISSUE TITLE
Block-Pair Error

### ISSUE THREAD

**Issue by ruffst** [ruffst/New-Production#20]
15:52:35.0104 [ERROR]  Keen:       Block-pair MyObjectBuilder_MotorRotor/LargeRotor MyObjectBuilder_MotorRotor/SmallRotor1 is not in the same block-variant group
15:52:35.0104 [ERROR]  Keen:       Block-pair MyObjectBuilder_MotorAdvancedRotor/LargeAdvancedRotor MyObjectBuilder_MotorAdvancedRotor/SmallAdvancedRotor1 is not in the same block-variant group
15:52:35.0104 [ERROR]  Keen:       Block-pair MyObjectBuilder_MotorAdvancedRotor/LargeHingeHead MyObjectBuilder_MotorAdvancedRotor/MediumHingeHead1 is not in the same block-variant group
15:52:35.0104 [ERROR]  Keen:       Block-pair MyObjectBuilder_MotorRotor/LargeRotor MyObjectBuilder_MotorRotor/SmallRotor1 is not in the same block-variant group
15:52:35.0104 [ERROR]  Keen:       Block-pair MyObjectBuilder_MotorAdvancedRotor/LargeAdvancedRotor MyObjectBuilder_MotorAdvancedRotor/SmallAdvancedRotor1 is not in the same block-variant group

**Comment by CaptainHarlock0006** [comment]
Wird bearbeiten in  "Block Fariant Group überarbeiten #28 "
