### ISSUE TITLE
Forschung Small Grid Triebwerke

### ISSUE THREAD

**Issue by BahaZoo** [ruffst/New-Production#29]
Bei den Meilensteinen für die Ionen und Hydrogentriebwerken sind die benötigten Materialien verkehrt herum.
Ionen brauchen die Raumfahrt Mats. die Hydros nicht
![Small hydro research](https://user-images.githubusercontent.com/96697123/148188888-f39b0fa3-4d1d-4c82-8a2b-8c0bf39370be.PNG)
![Small ions research](https://user-images.githubusercontent.com/96697123/148188896-0d14ed0a-ab33-4e2d-be0d-9e2de8fd6cc4.PNG)
.
5.1.22 9:55

**Comment by CaptainHarlock0006** [comment]
Nein da ist nichts falsch. Die Forschungselemente sind korrekt so. Schau bitte nochmal genau auf dein Bild, da kann man es sehen dass die Raumfahrt teile bei Ionen drin sind.
