### ISSUE TITLE
Basic gyros funktionieren nicht richtig

### ISSUE THREAD

**Issue by BahaZoo** [ruffst/New-Production#30]
Die dinger haben vermutlich zu wenig Drehmoment um ihr eigenes gewicht zu überwinden.
Testen: nimm ein fliegendes grid und gib gyro drauf, es bewegt sich ein wenig dann springt es in die ausgangs position zurück. versucht das mal selber um auszuschliessen das das  kein lokaler bug bei mir ist. habs am server und in solo getestet beides mal das gleiche ergebnis. 05.01.22 12:30

**Comment by CaptainHarlock0006** [comment]
Gyro Werte wurden angepasst. Nach dem Nächsten Modupdate bitte nochmal testen ob es nun besser geht.
