### ISSUE TITLE
small Grid Wheels crashen den server.

### ISSUE THREAD

**Issue by BahaZoo** [ruffst/New-Production#6]
placen von small grid wheels egalwelche lassen server und spiel abschmieren, lg stulle
[WheelCrash small grid.txt](https://github.com/ruffst/New-Production/files/7804647/WheelCrash.small.grid.txt)

**Comment by CaptainHarlock0006** [comment]
Ich weis schon woran das liegt. hab ich kommen sehen. Das ist das gleiche Problem wie mit den Pistons und Motoren.
Ich kümmere mich im laufe des Tages um einen Fix.

**Comment by CaptainHarlock0006** [comment]
Räder wurden gefixt. Beim nächten Mod Update kommt es auf den Server
